version: '3.9'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    ports:
      - 8501:8501
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  dynamodb-local:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:1.22.0
    command: "-jar DynamoDBLocal.jar"
    ports:
      - 8000:8000

  # 初期テーブル作成用のコンテナ
  init-dynamodb:
    image: public.ecr.aws/aws-cli/aws-cli:latest
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: key
      AWS_SECRET_ACCESS_KEY: key
    depends_on:
      - dynamodb-local
    command: >
      dynamodb create-table --table-name ChatSession
      --attribute-definitions
        AttributeName=SessionId,AttributeType=S
      --key-schema
        AttributeName=SessionId,KeyType=HASH
      --billing-mode PAY_PER_REQUEST
      --endpoint-url http://dynamodb-local:8000
