version: '3.9'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    environment:
      AWS_REGION: us-west-2
    ports:
      - 8501:8501
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - 8000:8000
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal 
